from fastapi import FastAPI, HTTPException, Header, Depends
from pydantic import BaseModel
import yt_dlp
import uvicorn
import logging
import os
import tempfile
import time
import re
from typing import Optional

# 配置日志
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="YuliusBox Video Extractor Microservice")

# --- 鉴权配置 ---
# 优先从环境变量读取密钥，避免源码明文泄露
SECRET_API_KEY = os.getenv("VPS_API_KEY", "change_this_secret_in_env")

async def verify_api_key(x_api_key: str = Header(...)):
    if x_api_key != SECRET_API_KEY:
        logger.warning(f"Unauthorized access attempt with invalid API Key")
        raise HTTPException(status_code=403, detail="Invalid API Key")

# --- 请求模型 ---
class ExtractRequest(BaseModel):
    url: str
    proxy: Optional[str] = None  # 支持传入代理: http://user:pass@ip:port

# --- Cookie 文件管理 ---
COOKIES_FILE_PATH = os.path.join(tempfile.gettempdir(), "douyin_cookies.txt")

def generate_cookie_file():
    """生成或更新 Cookie 文件"""
    douyin_cookies = os.getenv("DOUYIN_COOKIES")
    if not douyin_cookies:
        logger.info("No DOUYIN_COOKIES provided in environment variables.")
        return

    try:
        with open(COOKIES_FILE_PATH, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by YuliusBox microservice.\n\n")

            raw_cookies = douyin_cookies.split('; ')
            timestamp = int(time.time()) + 31536000 # 1 year validity

            for cookie in raw_cookies:
                if '=' in cookie:
                    try:
                        name, value = cookie.split('=', 1)
                        f.write(f".douyin.com\tTRUE\t/\tFALSE\t{timestamp}\t{name}\t{value}\n")
                        f.write(f"douyin.com\tTRUE\t/\tFALSE\t{timestamp}\t{name}\t{value}\n")
                    except Exception as e:
                        logger.warning(f"Failed to parse cookie segment: {cookie} - {e}")
        logger.info(f"Cookie file generated at: {COOKIES_FILE_PATH}")
    except Exception as e:
        logger.error(f"Failed to generate cookie file: {e}")

# 服务启动时尝试生成 Cookie 文件
generate_cookie_file()

# --- 核心提取逻辑 ---
@app.post("/api/extract", dependencies=[Depends(verify_api_key)])
async def extract_video(request: ExtractRequest):
    # 提取分享文案中的实际链接
    url_match = re.search(r'(https?://[^\s]+)', request.url)
    clean_url = url_match.group(0) if url_match else request.url.strip()

    logger.info(f"Processing extraction request for: {clean_url}")

    # yt-dlp 配置
    ydl_opts = {
        'format': 'best',
        'quiet': True,
        'no_warnings': True,
        'skip_download': True, # 核心：仅提取元数据与直链，绝不本地落盘
        'socket_timeout': 20,
    }

    try:
        if "douyin.com" in clean_url:
            if os.path.exists(COOKIES_FILE_PATH):
                ydl_opts['cookiefile'] = COOKIES_FILE_PATH
        elif request.proxy:
            ydl_opts['proxy'] = request.proxy
            logger.info("Using configured residential proxy for extraction.")

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(clean_url, download=False)

            video_url = info.get('url')
            title = info.get('title', 'Unknown Title')
            thumbnail = info.get('thumbnail')
            duration = info.get('duration_string')
            uploader = info.get('uploader')

            # 如果直接 url 为空，遍历 formats 获取最佳可用流
            if not video_url:
                formats = info.get('formats', [])
                best_format = next(
                    (f for f in formats if f.get('vcodec') != 'none' and f.get('acodec') != 'none'),
                    None
                )
                if best_format:
                    video_url = best_format.get('url')
                elif formats:
                    video_url = formats[-1].get('url')

            if not video_url:
                raise Exception("Failed to extract valid video stream URL from formats.")

            return {
                "success": True,
                "title": title,
                "videoUrl": video_url,
                "thumbnail": thumbnail,
                "duration": duration,
                "uploader": uploader
            }

    except yt_dlp.utils.DownloadError as e:
        logger.error(f"yt-dlp DownloadError: {str(e)}")
        return {
            "success": False,
            "error": "Video not found or access denied by platform."
        }
    except Exception as e:
        logger.error(f"Extraction General Error: {str(e)}")
        return {
            "success": False,
            "error": f"Extraction failed: {str(e)}"
        }

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
